influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  # env_file:
    # - 'env.influxdb'
  volumes:
    - /Users/ben/Development/docker/volumes/influxdb/data:/var/lib/influxdb

chronograf:
  image: 'chronograf'
  entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
  links:
    - influxdb
  ports:
    - "8888:8888"

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  # env_file:
    # - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    - /Users/ben/Development/docker/volumes/grafana/data:/var/lib/grafana